# GitHub Action - CI Pipeline dedicated to scan vulnerability on a Docker Image
# Capgemini - v1.0 - Xavier BRASSOUD <xavier.brassoud@capgemini.com>
#

name: CI - Scan Docker Image

on:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  ci-scan-docker-image:
    runs-on: ubuntu-latest

    steps:

    ##############################################################################
    ### STEP 1 : Run vulnerability scanner on container : vulnerables/web-dvwa ###
    ##############################################################################
    - name: Run Trivy vulnerability scanner on vulnerables/web-dvwa Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: postgres:alpine
        format: 'table'
        exit-code: 1

